apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  labels:
    app: app3

spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3

  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3-container
        image: nginx:latest
        ports:
        - containerPort: 80  # port inside the container (must match the app's exposed port)

        resources:
          limits:
            cpu: "500m"  # max 0.5 CPU cores
            memory: "256Mi"  # max 256MB memory
          requests:
            cpu: "250m"  # request 0.25 CPU cores initially
            memory: "128Mi"  # request 128MB memory initially
        volumeMounts:
        - name: nginx-content
          mountPath: /usr/share/nginx/html

      volumes:
      - name: nginx-content
        configMap:
          name: app3-content

      restartPolicy: Always



        # env:
        # - name: NODE_ENV
        #   value: "production"