# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  server_ip = "192.168.56.110"

  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.define "okocaS" do |control|
    control.vm.hostname = "okocaS"
    control.vm.network "private_network", ip: server_ip
    control.vm.provision "shell", path: "scripts/server.sh", env: {
      "SERVER_IP" => server_ip,
    }
  end
end