apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>App2</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                background-color: #f0f0f0;
            }
            h1 {
                font-size: 48px;
                color: #333;
            }
        </style>
    </head>
    <body>
        <h1>Hello World from App2</h1>
        <p>This is App2</p>
    </body>
    </html>